#!/bin/bash

cd /home/rafael/workspace/cister/client-java/publisher/test/pub1 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub1.txt &

cd /home/rafael/workspace/cister/client-java/publisher/test/pub2 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub2.txt &

cd /home/rafael/workspace/cister/client-java/publisher/test/pub3 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub3.txt &

cd /home/rafael/workspace/cister/client-java/publisher/test/pub4 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub4.txt &

cd /home/rafael/workspace/cister/client-java/publisher/test/pub5 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub5.txt &

cd /home/rafael/workspace/cister/client-java/publisher/test/pub6 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub6.txt &

cd /home/rafael/workspace/cister/client-java/publisher/test/pub7 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub7.txt &

cd /home/rafael/workspace/cister/client-java/publisher/test/pub8 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub8.txt &

cd /home/rafael/workspace/cister/client-java/publisher/test/pub9 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub9.txt &

cd /home/rafael/workspace/cister/client-java/publisher/test/pub10 || exit
nohup java -jar publisher-4.0.jar -d -daemon  &> pub10.txt &
